### ISSUE TITLE
Wrong convex hull results

### ISSUE THREAD

**Issue by cristianzamar** [brian3kb/graham_scan_js#11]
Hi.. I'm having some problems with the resulting convex hull points returned by  `getHull()`.
These are the points after adding with `addPoint(x, y)`:

```
0:ConvexHullGrahamScan.Point
  x:8.48206
  y:52.45522
1:ConvexHullGrahamScan.Point
  x:8.2489553
  y:52.67141
2:ConvexHullGrahamScan.Point
  x:8.28255
  y:52.6787
3:ConvexHullGrahamScan.Point
  x:8.2718435
  y:52.7555779
4:ConvexHullGrahamScan.Point
  x:7.41582
  y:53.11456
5:ConvexHullGrahamScan.Point
  x:11.62771
  y:52.08609
```

And the resulting hull points:

```
0:ConvexHullGrahamScan.Point
  x:8.2489553
  y:52.67141
1:ConvexHullGrahamScan.Point
  x:8.48206
  y:52.45522
2:ConvexHullGrahamScan.Point
  x:8.2718435
  y:52.7555779
3:ConvexHullGrahamScan.Point
  x:7.41582
  y:53.11456
```

the result is this:
![seleccion_001](https://cloud.githubusercontent.com/assets/4570494/13990113/deaabe84-f0f1-11e5-91fb-4fcc838ef4e3.jpg)

but it must be like this (green line):
![image](https://cloud.githubusercontent.com/assets/4570494/13990159/0def482c-f0f2-11e5-9733-a33782778f14.png)

I hope you can fix it soon.
Thanks in advance.

**Comment by quicky84** [comment]
You may want to check out my  #10 pull  request, it contains rather modest changes which enable the lib to produce the result you are expecting.

If you wish you may additionally run the following test

test('another hull test', 1, function() {
    var points = [
        {'x': 8.48206, 'y': 52.45522}, {'x': 8.2489553, 'y': 52.67141}, {'x': 8.28255, 'y': 52.6787},
        {'x': 8.2718435, 'y': 52.7555779}, {'x': 7.41582, 'y': 53.11456}, {'x': 11.62771, 'y': 52.08609}
    ];
    var expectedHull = [
         {'x': 11.62771, 'y': 52.08609}, {'x': 7.41582, 'y': 53.11456}, {'x': 8.48206, 'y': 52.45522}
    ];

    var testGSHull = new ConvexHullGrahamScan();
    points.forEach( function(p){ testGSHull.addPoint(p['x'], p['y']); } );    
    equal(testGSHull.getHull(), expectedHull, 'Check output hull is as expected.');
});

**Comment by cristianzamar** [comment]
@quicky84 thanks for your replay!!
I solved this problem by passing the lat/long points as strings :S
However, I will test your solution as it looks more natural.
Greetings
