### ISSUE TITLE
Unexpected results on inset squares

### ISSUE THREAD

**Issue by jlewin** [brian3kb/graham_scan_js#7]
I ran the following sample data through the library:
```
var graham_scan = require('graham_scan');
var gscan = new graham_scan();

gscan.addPoint(2, 2);
gscan.addPoint(2, -2);
gscan.addPoint(-2, -2);
gscan.addPoint(-2, 2);

gscan.addPoint(3, 3);
gscan.addPoint(3, -3);
gscan.addPoint(-3, -3);
gscan.addPoint(-3, 3);

gscan.addPoint(4, 4);
gscan.addPoint(4, -4);
gscan.addPoint(-4, -4);
gscan.addPoint(-4, 4);

gscan.addPoint(5, 5);
gscan.addPoint(-5, 5);
gscan.addPoint(-5, -5);
gscan.addPoint(5, -5);

var hull = gscan.getHull();
for (var i = 0; i < hull.length; i++)
{
  console.log(i, hull[i]);
};
```

I expected the hull to contain only the four green points as depicted below and was surprised to the see the four additional points in red and a non-ccw ordering:

![Results](http://i.imgur.com/X3QFJ4C.png)

**Hull Results**

1. { x: -5, y: -5 }
2. { x: 5, y: -5 }
3. { x: 3, y: 3 } *
4. { x: 2, y: 2 } *
5. { x: -4, y: -4 } *
6. { x: -3, y: -3 } *
7. { x: 5, y: 5 }
8. { x: -5, y: 5 }

After a small amount of research it seems plausible that this occurs because these points are collinear and share the same polar angle with the anchor point but part of me worries that with such a simple failing case I'm just confused with the setup, limitations or use of the library or problem space. If the later is the issue, please close and disregard.

**Comment by brian3kb** [comment]
@jlewin Looks like there's a bug in the checkPoints method, collinear points sharing the same polar angle are being passed through to the resultant hull array, when they should be being removed. Apologies for this, I'll clean this up, add an example, test and then push an update later this evening.

I never expected this to get used by anyone other than myself to be honest! and I've only ever used it in conjunction with plotting on geographical maps, which very rarely have points that meet this condition.

Thanks for taking the time to open the issue with the great test data :)

**Comment by billyhickman1** [comment]
I use it! It's awesome, thank you! :)

On Wednesday, 16 December 2015, Brian Barnett <notifications@github.com>
wrote:

> @jlewin <https://github.com/jlewin> Looks like there's a bug in the
> checkPoints method, collinear points sharing the same polar angle are being
> passed through to the resultant hull array, when they should be being
> removed. Apologies for this, I'll clean this up, add an example, test and
> then push an update later this evening.
>
> I never expected this to get used by anyone other than myself to be
> honest! and I've only ever used it in conjunction with plotting on
> geographical maps, which very rarely have points that meet this condition.
>
> Thanks for taking the time to open the issue with the great test data :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brian3kb/graham_scan_js/issues/7#issuecomment-165070465>
> .
>


-- 
*Billy Hickman*
*me@billyhickman.com <me@billyhickman.com>*
*Computer Science Student @ Cardiff University*

**Comment by jlewin** [comment]
Nice! Thanks so much for taking the time to look into this, for fixing the issue and especially for sharing your implementation and efforts.

**Comment by brian3kb** [comment]
I forgot to bump the npm version last night, so that's all done :) Thanks for the kind comments guys!
